// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTV9dU-5S5caVMBmiJxCCLfLRdwkOhkE',
    appId: '1:93211325712:web:ff3c37993c8435571ba195',
    messagingSenderId: '93211325712',
    projectId: 'rebuilding-e670a',
    authDomain: 'rebuilding-e670a.firebaseapp.com',
    storageBucket: 'rebuilding-e670a.firebasestorage.app',
    measurementId: 'G-E7CRT02P46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-sZpHxa12PNZ9PrRE6LgDhsRXnpUiU70',
    appId: '1:93211325712:android:97de9544281c76c71ba195',
    messagingSenderId: '93211325712',
    projectId: 'rebuilding-e670a',
    storageBucket: 'rebuilding-e670a.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANuSoIpzjTiwxKuqU3wO7wMJPRegX0-JY',
    appId: '1:93211325712:ios:fa8d6a6b88ef3dff1ba195',
    messagingSenderId: '93211325712',
    projectId: 'rebuilding-e670a',
    storageBucket: 'rebuilding-e670a.firebasestorage.app',
    iosBundleId: 'com.example.rebuildingFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANuSoIpzjTiwxKuqU3wO7wMJPRegX0-JY',
    appId: '1:93211325712:ios:fa8d6a6b88ef3dff1ba195',
    messagingSenderId: '93211325712',
    projectId: 'rebuilding-e670a',
    storageBucket: 'rebuilding-e670a.firebasestorage.app',
    iosBundleId: 'com.example.rebuildingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTV9dU-5S5caVMBmiJxCCLfLRdwkOhkE',
    appId: '1:93211325712:web:3bf3fb559d99bce81ba195',
    messagingSenderId: '93211325712',
    projectId: 'rebuilding-e670a',
    authDomain: 'rebuilding-e670a.firebaseapp.com',
    storageBucket: 'rebuilding-e670a.firebasestorage.app',
    measurementId: 'G-NM2W9EEYVS',
  );

}