// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtoCAqds0j887mrLizPyy3f2NaHsEBF9M',
    appId: '1:332068293193:web:3771406722b77955060d98',
    messagingSenderId: '332068293193',
    projectId: 'rebuilding-5820d',
    authDomain: 'rebuilding-5820d.firebaseapp.com',
    storageBucket: 'rebuilding-5820d.firebasestorage.app',
    measurementId: 'G-HT71XX9M92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGURYE7-sSxGWICRZ0tIgwINbhJTzSwok',
    appId: '1:332068293193:android:0d8162d93dbf2adf060d98',
    messagingSenderId: '332068293193',
    projectId: 'rebuilding-5820d',
    storageBucket: 'rebuilding-5820d.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC57HM7W3djHPgTDNA2EKslAnwH7jZ94BA',
    appId: '1:332068293193:ios:2ebf1093d41ce529060d98',
    messagingSenderId: '332068293193',
    projectId: 'rebuilding-5820d',
    storageBucket: 'rebuilding-5820d.firebasestorage.app',
    iosBundleId: 'com.example.rebuildingFlutter',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC57HM7W3djHPgTDNA2EKslAnwH7jZ94BA',
    appId: '1:332068293193:ios:2ebf1093d41ce529060d98',
    messagingSenderId: '332068293193',
    projectId: 'rebuilding-5820d',
    storageBucket: 'rebuilding-5820d.firebasestorage.app',
    iosBundleId: 'com.example.rebuildingFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtoCAqds0j887mrLizPyy3f2NaHsEBF9M',
    appId: '1:332068293193:web:6fd81f5f3e599575060d98',
    messagingSenderId: '332068293193',
    projectId: 'rebuilding-5820d',
    authDomain: 'rebuilding-5820d.firebaseapp.com',
    storageBucket: 'rebuilding-5820d.firebasestorage.app',
    measurementId: 'G-PP3M6XWFML',
  );

}